"""empty message

Revision ID: 24633ab43731
Revises: 2a55ba18524e
Create Date: 2025-06-03 15:04:08.586250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24633ab43731'
down_revision = '2a55ba18524e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
