"""Add task_date and note_date

Revision ID: fc03c03cc1da
Revises: 
Create Date: 2025-06-03 10:36:45.541414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc03c03cc1da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_date', sa.Date(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('task_date')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('note_date')

    # ### end Alembic commands ###
